- diagonal
- linspace 
- how does numpy vector stores element in  memory
- diag
- flatten
- inplace parameters should not be assigned to a new variable
    - ex :  we cannot  write b=a.sort()
    - but we can write b=sorted(a)
    - same example in reshape is given
- hstack and vstack to combine data of different people
    - hstack : understand imp
    - vstack : similar like normal array


In [1]:
import numpy as np
import random

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr=np.linspace?

In [ ]:
arr=np.linspace

In [5]:
arr=np.linspace(0,10,9)
arr

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [6]:
arr=np.ones((2,3) , dtype='int')

In [7]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.diagonal(a=arr)

array([1, 1])

In [9]:
a=np.array([1,2,3,4,5])
print(a , a.shape)

[1 2 3 4 5] (5,)


In [10]:
b=np.arange(5)
print(b.shape)
b

(5,)


array([0, 1, 2, 3, 4])

In [11]:
d=np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(d.shape)
d
e=np.diagonal(d)
print(e , e.shape)

(3, 3)
[1 5 9] (3,)


In [12]:
c=np.ones((2,3) , dtype='int')
print(c.shape)
c

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
f=np.zeros((2,3))
print(f.ndim)
print(f.shape)
print(f)

2
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
a=np.array([[1,2,3],[10,20,30],[100,200,300]])
np.diagonal(a)

array([  1,  20, 300])

In [15]:
c=np.diag((1,2,3))
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
d=c.flatten()

In [17]:
d

array([1, 0, 0, 0, 2, 0, 0, 0, 3])

# Reshape vs resize
- reshape is not inplace 
- resize = inplace = True

In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a.shape)

(4, 3)


In [19]:
## b=a.resize(2,6) this is invalid
a.resize(2,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [20]:
b=a.reshape(2,6)
print(b,b.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6)


In [21]:
x=np.hstack([[1,2,3],[4,5,6]])
print(x)

[1 2 3 4 5 6]


In [22]:
y=np.vstack([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
z=np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

## Important logic

In [24]:
a=np.array([[1,2,3] ,[4,5,6]])
b=np.array([[10,20,30],[40,50,60] ] )

c=np.hstack((a,b) )
d=np.vstack((a,b))

print(c)
print(d)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [25]:
a=np.array([[10,2,99],
          [5,1,90],
           [14,2,99],
           [4,5,4]])
print(a)

[[10  2 99]
 [ 5  1 90]
 [14  2 99]
 [ 4  5  4]]


In [26]:
print("Max : " , a.max())
print("Max (row-wise): " , a.max(axis=0))
print("Min : " , a.min())
print("Min : column-wise" , a.min(axis=1))
print("Min element index : " , a.argmin())
print("Max element index : " , a.argmax())
print("Min element indexes(rowwise) : " , a.argmin(axis=0))
print("Max element indexes(columnwise) : " , a.argmax(axis=1))
print("Standard deviation : " , a.std())
print("mean : ",a.mean())
print("mean (column-wise): ",a.mean(axis=1))
print("mean (row-wise): ",a.mean(axis=0))

Max :  99
Max (row-wise):  [14  5 99]
Min :  1
Min : column-wise [2 1 2 4]
Min element index :  4
Max element index :  2
Min element indexes(rowwise) :  [3 1 3]
Max element indexes(columnwise) :  [2 2 2 1]
Standard deviation :  39.5146773012538
mean :  27.916666666666668
mean (column-wise):  [37.         32.         38.33333333  4.33333333]
mean (row-wise):  [ 8.25  2.5  73.  ]


In [27]:
print(a)

[[10  2 99]
 [ 5  1 90]
 [14  2 99]
 [ 4  5  4]]


## imp

b=a[2: , -2::-1]
print(b)

## read verdict from sir's code


#  + vs += read imp

In [28]:
list=list()
list()

TypeError: 'list' object is not callable

In [ ]:
list=list()
list

# copying very imp concept

In [ ]:
a=np.array([[ 1,  2,  3],
 [ 4 , 5,  6],
 [10 ,20, 30],
 [40 ,50 ,60]])
print(a)

In [ ]:
b=a[0:2 ,0:2 ]
b

In [ ]:
b[: , : ]=0
print(b)
print(a)

## i changed b but it also made changes in a 


In [ ]:
## soluition
a=np.array([[ 1,  2,  3],
 [ 4 , 5,  6],
 [10 ,20, 30],
 [40 ,50 ,60]])
print(a)
c=a[0:2 , 0:2].copy()
c

In [ ]:
c[ : , : ]=100
print(c)
print(a)