## Operations on arrays

In [1]:
import numpy as np

In [2]:
n=np.array([[1,2],[3,4]])
m=np.array([[5,6],[7,8]])

# ELEMENT WISE OPERATIONS

In [23]:
s=np.add(m,n)
d=np.subtract(m,n)
p=np.multiply(m,n)
q=np.divide(m,n)

## alternate=m.add(n) this is not supported

In [24]:
print(s,d,p,q , sep="\n \n")

[[ 6  8]
 [10 12]]
 
[[4 4]
 [4 4]]
 
[[ 5 12]
 [21 32]]
 
[[5.         3.        ]
 [2.33333333 2.        ]]


In [25]:
print(m+n)

[[ 6  8]
 [10 12]]


In [26]:
print(m-n)

[[4 4]
 [4 4]]


In [27]:
print(m*n)

[[ 5 12]
 [21 32]]


In [28]:
print(m/n)

[[5.         3.        ]
 [2.33333333 2.        ]]


In [29]:
print(m%n)

[[0 0]
 [1 0]]


In [30]:
print(m**n)

[[   5   36]
 [ 343 4096]]


# MATRIX MULTIPLICATION

In [33]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a.dot(b))
## treat like a vector dot product ==> gives a scalar ( 1*5 + 2*6 + 3*7 + 4*8)

70


In [32]:
print(m.dot(n))
print(m)
print(np.dot(m,n))

[[23 34]
 [31 46]]
[[5 6]
 [7 8]]
[[23 34]
 [31 46]]


In [44]:
print(np.sum(a))

10


In [49]:
print(m)

print()
print(np.sum(m))

print()
print(np.sum(m,axis=0))
print(np.sum(m,axis=1))

[[5 6]
 [7 8]]

26

[12 14]
[11 15]


# MERGING & RESHPING TWO ARRAYS
AXIS = 0 ( | = COLUMNWISE = ROW IS CHANGING  COLUMN IS SAME)
AXIS = 1 ( - = ROWWISE = COLUMN IS CHANGING  ROW IS SAME)

In [48]:
s=np.array([1,2,3,4])
k=np.array([5,6,7,8])
print(np.stack((s,k),axis=1))
print()
print(np.stack((s,k),axis=0))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [50]:
a=np.stack((s,k),axis=1)
b=np.stack((s,k),axis=0)


In [52]:
print(a)
a=a.reshape((2,4))
print()
print(a)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 5 2 6]
 [3 7 4 8]]


In [57]:
print(b)
b=b.reshape((4,2))
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
