## Types of arrays in numpy
- zeros
- ones
- identity (eye)
- constants (full ) 
- random.random
- arange

In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b=np.zeros((3,2))
print(b)
b=np.zeros((3,2) , dtype=np.int32)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]]


In [15]:
c=np.ones((2,4))
print(c)
c=np.ones((2,4) , dtype=np.int64)
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]]


In [26]:
d=np.eye((4) ,dtype=np.float32)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
e=np.full((2,5) , 7 )
print(e)
e=np.full((2,5) , 7 ,dtype=np.float32)
print(e)
np.full?

[[7 7 7 7 7]
 [7 7 7 7 7]]
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [33]:
f=np.random.random((4,2))
print(f)

[[0.93531795 0.22556619]
 [0.55277703 0.92815678]
 [0.05357293 0.16848131]
 [0.447645   0.00121564]]


In [40]:
g=np.arange((10))
print(g)
h=np.arange((10))+5
print(h)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
