In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12] ])
c=np.array([[1,2,3,4,5,6,7,8]])

In [5]:
d=a[0:5]
print(d ,type(d), d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)


In [6]:
z=np.array([[1,"hello",True] , [1,2]])

In [7]:
print(z)
print(z[0], type(z[0]))

[list([1, 'hello', True]) list([1, 2])]
[1, 'hello', True] <class 'list'>


In [8]:
y=b[ : , 2]
print(x , y, sep= "\n")

NameError: name 'x' is not defined

In [9]:
a=np.array([[1,2,3] , [4,5,6], [7,8,9] ])
print(a[0] , type(a[0]) , a[0].shape )

[1 2 3] <class 'numpy.ndarray'> (3,)


In [10]:
print(a[ 2 : 3, : ])
print(a[ 2 : 3, : ].shape)

[[7 8 9]]
(1, 3)


In [11]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b.shape)


(4, 4)


In [12]:
s=b[ 1:3 , 1: ]
print(s)
print(s.shape)

q= np.reshape(s , (3,2))


[[ 6  7  8]
 [10 11 12]]
(2, 3)


In [13]:
print(q,type(q),q.shape)

[[ 6  7]
 [ 8 10]
 [11 12]] <class 'numpy.ndarray'> (3, 2)


In [14]:
r=np.transpose(s)
print(r)
print(r.shape)

[[ 6 10]
 [ 7 11]
 [ 8 12]]
(3, 2)


In [16]:
z=np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])


In [18]:
print( z[ -2: , -3 :-1 ])

[[ 6  7]
 [10 11]]


In [20]:
z[1 , : ]=-1
z[ : ,2]=-2
print(z)

[[ 1  2 -2  4]
 [-1 -1 -2 -1]
 [ 9 10 -2 12]]


In [22]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y=np.transpose(y)
print(y)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [29]:
x=np.array([[1,2,3,4],[5,6,7,8]])
##np.reshape?
x2=np.reshape(x, (4,2) )
x3=np.reshape(x, (4,2) )


print(x2)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [33]:
h=np.array([[1,2],[3,4],[5,6]])
h1=np.reshape( h , (2,3))
h2=np.transpose(h)

In [34]:
print(h1)
print(h2)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


In [35]:
a=np.array( [1,2,3,4] )
b=np.array( [10,20,30,40] )

In [36]:
c=np.stack( (a,b) , axis=1 )
d=np.stack( (a,b) , axis=0 )

In [37]:
print(c)
print(d)

[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]]
[[ 1  2  3  4]
 [10 20 30 40]]


In [38]:
a=np.array( [[ 1,2,3], [4,5,6]])
b=np.array( [  [1,2 ] ,[3,4], [5,6] ])
print(np.dot(a,b) , np.dot(a,b).shape)

[[22 28]
 [49 64]] (2, 2)


In [41]:
c=np.array([1,2,3,4])
d=np.array([10,20,30,40])
print(np.dot(c,d))

300
