## Random module : already present in numpy
- rand = random values in a given shape
- randn = returns samples from standard normal distribution
- randint = return random integers in a particular range
- random = returns a random float in half open interval [0,1)
- choice = generates a random sample from a a given 1 d array
- shuffle + seed = shuffles the content of an array

alternate ways of importing = from numpy import random as rd

In [1]:
import numpy as np

In [2]:
from numpy import random as rd

In [3]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [12]:

rd.shuffle(a)
print(a)
np.random.shuffle(a)
print(a)


## not valid :numpy.random.shuffle(a)

[11  7  6 10  5 14  8  9 13 12]
[ 6  9  5 11 12 13  7 14  8 10]


In [5]:
element=np.random.choice(a)
print(element)

element2=np.random.choice(a , size=2)
print(element2)

9
[13 14]


In [6]:
b=np.random.rand(2,3)
print(b)

[[0.45720481 0.43069857 0.93912779]
 [0.77838924 0.71597052 0.8027575 ]]


In [7]:
##return values from standard normal distr
c=np.random.randn(2,4)
print(c)

[[ 0.04026035 -0.90312288  0.17532267  0.19443089]
 [-0.53524902  0.77735121  0.17133845 -0.44285144]]


In [8]:
d=np.random.randint( 5, 10 , 3 )
print(d ,type(d),d.shape ,sep= "\t")
print()
e=np.random.randint( 5, 10 , (2,3) )
print(e ,type(e),e.shape,sep= "\t")

[8 6 6]	<class 'numpy.ndarray'>	(3,)

[[8 9 5]
 [6 8 9]]	<class 'numpy.ndarray'>	(2, 3)


In [9]:
f=np.random.random((2,3))
print(f)

[[0.78331447 0.41253884 0.03417131]
 [0.62402999 0.66063573 0.29849529]]
