- accessing and changing data along a row or a column
- transpose and reshape
- stack the vectors to form a 2d-array
- dot product
- MaxMin , Mean , median , sd , variance , average
- ndim

In [1]:
import numpy as np

# Part -2


In [2]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b=np.array(a)

In [3]:
b[1 , 1: ]=30      # along a row 
b[ : , 2  ]=20     # along a column
print(b)

[[ 1  2 20  4]
 [ 5 30 20 30]
 [ 9 10 20 12]
 [13 14 20 16]]


In [4]:
c=a.transpose()
print(c)

print()
## whenever we reshape it , consider all the elements to be store linearly 

d=c.reshape((2,8))
print(d  , d.shape , type(d))

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 1  5  9 13  2  6 10 14]
 [ 3  7 11 15  4  8 12 16]] (2, 8) <class 'numpy.ndarray'>


In [5]:
x=np.array([10,20,30,40])
y=np.array([100,200,300,400])

z1 = np.stack((x,y) , axis =0 )   # (2,4)
z2 = np.stack((x,y) , axis =1 )   # (4,2)

print(z1, z1.shape)
print()
print(z2 , z2.shape)

## in order to reverse the axis = TRANSPOSE (simple)
print()
print(z2.transpose())

[[ 10  20  30  40]
 [100 200 300 400]] (2, 4)

[[ 10 100]
 [ 20 200]
 [ 30 300]
 [ 40 400]] (4, 2)

[[ 10  20  30  40]
 [100 200 300 400]]


In [6]:
## dot product of two vectors of same length
print(x.dot(y))

## dot product of two 2d matrices = (2,3) . ( 3,4) = (2, 4) 
p=np.array([[1,2,3],[4,5,6]])
q=np.array([[10],[20],[30]])
print(np.dot(p,q))

30000
[[140]
 [320]]


In [7]:
a=(np.arange(9)+1)*2
print(a.mean())
print(a.max(), a.min())
print(a.std())


10.0
18 2
5.163977794943222


In [8]:
print(a.ndim)

1
