# Deeper Dive in numpy

- Storing of list object vs numpy array in memory
- linspace
- diag and diagonal
- changing dtype in an easy way
- flatten()
- reshape vs resize
- stack v&h
- argmin and argmax
- + vs +=
- Need and use of .copy()
- 

In [1]:
import numpy as np

In [5]:
l=list(range(10))
print(l)

## alternative 
l=np.arange(10)
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [22]:
np.linspace(0 , 10 , 5)
## divides 0-10 in 5 equal parts where 0 and 5 are included

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

l=np.diagonal(a)
print(l , type(l))
## returns an array of digonal elements of the given array

print()

l=np.diag((1,2,3))
print(l)
## returns an array which has the diagonal elements of a tuple

[1 5 9] <class 'numpy.ndarray'>

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
np.ones((2,3) , dtype='i')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [31]:
np.ones((2,3) , dtype='f')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [38]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.flatten())

b=np.array([[1],[2],[3]])
print(b.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3]


### Reshape : inplace = False    &        Resize : inplace = True
#### Conclusion :  1.  if by default inplace = true then there will be no returning of the object we have to print it
#### 2.   if by default inplace = true then we cannot assign it to another variable directly

In [43]:
print(a.shape)
a.reshape((2,6))

(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [45]:
a.resize((2,6))
### b=a.resize((2,6,)) this will give me wrong result
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [51]:
## np.h/vstack is a new way of creating an a new array but stacked array

a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=np.array([[1,2,3],[4,5,6]])
c=np.array( [ [7,8,9] , [10,11,12] ] )

np.hstack([b,c])    
## horizontallly ek ke aage ek rakh dega
##[[1,2,3]  +  [ [7,8,9]        = [ [1,2,3,7,8,9]
#  [4,5,6] ]  +   [10,11,12]  ]  =  [4,5,6,10,11,12] ]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
np.vstack([b,c])    
## verticallly ek ke neeche ek rakh dega
##[[1,2,3]            
#  [4,5,6] ]  

#    +     

#[ [7,8,9]
#    [10,11,12]  ]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
print("Max : " , a.max())
print("Max (row-wise): " , a.max(axis=0))
print("Min : " , a.min())
print("Min : column-wise" , a.min(axis=1))
print("Min element index : " , a.argmin())
print("Max element index : " , a.argmax())
print("Min element indexes(rowwise) : " , a.argmin(axis=0))
print("Max element indexes(columnwise) : " , a.argmax(axis=1))
print("Standard deviation : " , a.std())
print("mean : ",a.mean())
print("mean (column-wise): ",a.mean(axis=1))
print("mean (row-wise): ",a.mean(axis=0))

Max :  12
Max (row-wise):  [10 11 12]
Min :  1
Min : column-wise [ 1  4  7 10]
Min element index :  0
Max element index :  11
Min element indexes(rowwise) :  [0 0 0]
Max element indexes(columnwise) :  [2 2 2 2]
Standard deviation :  3.452052529534663
mean :  6.5
mean (column-wise):  [ 2.  5.  8. 11.]
mean (row-wise):  [5.5 6.5 7.5]


## Need and use of .copy()

In [56]:
print(a.shape)
a

(4, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
b=a[1: , 1:]
b

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [58]:
b[: , : ]=20

In [59]:
### 1. all the elements of b will become =20
### 2. will the values of a also change ? ans =Yes
print(b)
print(a)

[[20 20]
 [20 20]
 [20 20]]
[[ 1  2  3]
 [ 4 20 20]
 [ 7 20 20]
 [10 20 20]]


In [60]:
## THIS IS BECAUSE WE REFERNCED b VARIABE TO a . This can be understood as  : if we take out a portion from 'a' and name it b
## after doing changes in b we have to put it back in 'a'

In [62]:
## Solution
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=a[1 : , 1 : ].copy()
b

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [63]:
b[: , : ] =20
print(b)
print(a)

[[20 20]
 [20 20]
 [20 20]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
