In [21]:
import numpy as np

In [22]:
p = [int(x) for x in input().split()]

3 2


In [23]:
x = [int(x) for x in input().split()]
y = [int(x) for x in input().split()]


0 3 4 
2 4


In [24]:
lx = []
for i in range(p[0]):
    for j in range(i+1,p[0]):
        lx.append( np.array( [(x[i],0 ,x[j],0)] ) ) 
lx = np.array(lx)
lx = np.concatenate(lx , axis=0)
lx = lx.repeat(len(y) ,axis=0)
lx    

array([[0, 0, 3, 0],
       [0, 0, 3, 0],
       [0, 0, 4, 0],
       [0, 0, 4, 0],
       [3, 0, 4, 0],
       [3, 0, 4, 0]])

In [25]:
y1 = y*len(x)
ly = np.array(y1)
ly =np.reshape(ly , (ly.shape[0],1))
ly1 = np.zeros_like(y1)
ly1 =np.reshape(ly1 , (ly1.shape[0],1))
ly = np.concatenate((ly1,ly) , axis = 1)
ly

array([[0, 2],
       [0, 4],
       [0, 2],
       [0, 4],
       [0, 2],
       [0, 4]])

In [26]:
X = np.concatenate((lx,ly), axis=1)
X

array([[0, 0, 3, 0, 0, 2],
       [0, 0, 3, 0, 0, 4],
       [0, 0, 4, 0, 0, 2],
       [0, 0, 4, 0, 0, 4],
       [3, 0, 4, 0, 0, 2],
       [3, 0, 4, 0, 0, 4]])

In [33]:
def givemeans3(p1,p2,p3):
    b= ((p3-p1)**2).sum()
    p= ((p3-p2)**2).sum()
    h= ((p2-p1)**2).sum()
    
    
    if h == p+b:
        print(p,b,h)
        return 1
    else:
        return 0

In [34]:
for i in X:
    p1 = np.array([ i[0] , i[1] ])
    p2 = np.array([ i[2] , i[3] ])
    p3 = np.array([ i[4] , i[5] ])
    print(givemeans3(p1,p2,p3))
    
    p2 = np.array([ i[0] , i[1] ])
    p3 = np.array([ i[2] , i[3] ])
    p1 = np.array([ i[4] , i[5] ])
    print(givemeans3(p1,p2,p3))

    p3 = np.array([ i[0] , i[1] ])
    p1 = np.array([ i[2] , i[3] ])
    p2 = np.array([ i[4] , i[5] ])    
    print(givemeans3(p1,p2,p3))

0
0
4 9 13
1
0
0
16 9 25
1
0
0
4 16 20
1
0
0
16 16 32
1
0
0
0
0
0
0


In [35]:
ly = []
for i in range(p[1]):
    for j in range(i+1,p[1]):
        ly.append( np.array( [(0,y[i],0 ,y[j])] ) ) 
ly = np.array(ly)
ly = np.concatenate(ly , axis=0)
ly = ly.repeat(len(x) ,axis=0)
ly

array([[0, 2, 0, 4],
       [0, 2, 0, 4],
       [0, 2, 0, 4]])

In [43]:
x1 = x*int( len(ly) / len(x)) 
print(x1)
lx = np.array(x1)
lx =np.reshape(lx , (lx.shape[0],1))
lx1 = np.zeros_like(x1)
lx1 =np.reshape(lx1 , (lx1.shape[0],1))
lx = np.concatenate((lx,lx1) , axis = 1)
lx

[0, 3, 4]


array([[0, 0],
       [3, 0],
       [4, 0]])

In [44]:
Y = np.concatenate((lx,ly), axis=1)
Y

array([[0, 0, 0, 2, 0, 4],
       [3, 0, 0, 2, 0, 4],
       [4, 0, 0, 2, 0, 4]])

In [46]:
X = np.concatenate((X,Y) ,axis = 0)
X

array([[0, 0, 3, 0, 0, 2],
       [0, 0, 3, 0, 0, 4],
       [0, 0, 4, 0, 0, 2],
       [0, 0, 4, 0, 0, 4],
       [3, 0, 4, 0, 0, 2],
       [3, 0, 4, 0, 0, 4],
       [0, 0, 0, 2, 0, 4],
       [3, 0, 0, 2, 0, 4],
       [4, 0, 0, 2, 0, 4]])

In [45]:
for i in Y:
    p1 = np.array([ i[0] , i[1] ])
    p2 = np.array([ i[2] , i[3] ])
    p3 = np.array([ i[4] , i[5] ])
    print(givemeans3(p1,p2,p3))
    
    p2 = np.array([ i[0] , i[1] ])
    p3 = np.array([ i[2] , i[3] ])
    p1 = np.array([ i[4] , i[5] ])
    print(givemeans3(p1,p2,p3))

    p3 = np.array([ i[0] , i[1] ])
    p1 = np.array([ i[2] , i[3] ])
    p2 = np.array([ i[4] , i[5] ])    
    print(givemeans3(p1,p2,p3))

0
0
0
0
0
0
0
0
0
