In [83]:
import numpy as np

In [84]:
p = [int(x) for x in input().split()]

3 4


In [85]:
x = [int(x) for x in input().split()]
y = [int(x) for x in input().split()]



1 2 3
1 2 3 4


In [6]:
x = np.array(x)
y = np.array(y)
x=np.reshape(x , (x.shape[0],1))
y=np.reshape(y , (y.shape[0],1))

x1 = np.zeros_like(x)
y1 = np.zeros_like(y)

x = np.concatenate((x,x1) , axis = 1 )
y = np.concatenate((y1,y) , axis = 1 )

print(x,y)

[[ 0  0]
 [ 3  0]
 [-4  0]] [[0 2]
 [0 3]]


In [7]:
x1 = np.repeat(x , x.shape[0] ,axis = 0)
x2 = list(x)
x2 = np.array(x2*x.shape[0])


In [8]:
X =np.concatenate((x1,x2) , axis = 1)
n= X.shape[0]
X

array([[ 0,  0,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0, -4,  0],
       [ 3,  0,  0,  0],
       [ 3,  0,  3,  0],
       [ 3,  0, -4,  0],
       [-4,  0,  0,  0],
       [-4,  0,  3,  0],
       [-4,  0, -4,  0]])

In [9]:
X = np.repeat(X , y.shape[0] ,axis=0)
X

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  3,  0],
       [ 0,  0, -4,  0],
       [ 0,  0, -4,  0],
       [ 3,  0,  0,  0],
       [ 3,  0,  0,  0],
       [ 3,  0,  3,  0],
       [ 3,  0,  3,  0],
       [ 3,  0, -4,  0],
       [ 3,  0, -4,  0],
       [-4,  0,  0,  0],
       [-4,  0,  0,  0],
       [-4,  0,  3,  0],
       [-4,  0,  3,  0],
       [-4,  0, -4,  0],
       [-4,  0, -4,  0]])

In [10]:
y1 = list(y)*n
y1 = np.array(y1)
y1

array([[0, 2],
       [0, 3],
       [0, 2],
       [0, 3],
       [0, 2],
       [0, 3],
       [0, 2],
       [0, 3],
       [0, 2],
       [0, 3],
       [0, 2],
       [0, 3],
       [0, 2],
       [0, 3],
       [0, 2],
       [0, 3],
       [0, 2],
       [0, 3]])

In [11]:
X = np.concatenate((X,y1),axis =1)
X

array([[ 0,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0,  3],
       [ 0,  0,  3,  0,  0,  2],
       [ 0,  0,  3,  0,  0,  3],
       [ 0,  0, -4,  0,  0,  2],
       [ 0,  0, -4,  0,  0,  3],
       [ 3,  0,  0,  0,  0,  2],
       [ 3,  0,  0,  0,  0,  3],
       [ 3,  0,  3,  0,  0,  2],
       [ 3,  0,  3,  0,  0,  3],
       [ 3,  0, -4,  0,  0,  2],
       [ 3,  0, -4,  0,  0,  3],
       [-4,  0,  0,  0,  0,  2],
       [-4,  0,  0,  0,  0,  3],
       [-4,  0,  3,  0,  0,  2],
       [-4,  0,  3,  0,  0,  3],
       [-4,  0, -4,  0,  0,  2],
       [-4,  0, -4,  0,  0,  3]])

In [12]:
def givemeans(p1,p2,p3):
    s1 = ((p1-p2)**2).sum() + ((p2-p3)**2).sum() - ((p1-p3)**2).sum()
    s2 = ((p2-p3)**2).sum() + ((p3-p1)**2).sum() - ((p1-p2)**2).sum()
    s3 = ((p3-p1)**2).sum() + ((p1-p2)**2).sum() - ((p2-p3)**2).sum()
    
    if s1==0 or s2==0 or s3==0:
        return 1
    
    else:
        return 0

In [13]:
j=0
k= len(X)
for i in X:
    
    
    p1 = np.array([ i[0] , i[1] ])
    p2 = np.array([ i[2] , i[3] ])
    p3 = np.array([ i[4] , i[5] ])
    
    if p1[0]==p2[0] and p1[1]==p2[1]:
        continue
    print(p1,p2,p3)
    j=j+1
    #print(givemeans(p1,p2,p3) )

[0 0] [3 0] [0 2]
[0 0] [3 0] [0 3]
[0 0] [-4  0] [0 2]
[0 0] [-4  0] [0 3]
[3 0] [0 0] [0 2]
[3 0] [0 0] [0 3]
[3 0] [-4  0] [0 2]
[3 0] [-4  0] [0 3]
[-4  0] [0 0] [0 2]
[-4  0] [0 0] [0 3]
[-4  0] [3 0] [0 2]
[-4  0] [3 0] [0 3]


In [86]:
lx = []
for i in range(p[0]):
    for j in range(i+1,p[0]):
        lx.append( np.array( [(x[i],0 ,x[j],0)] ) ) 
    

In [87]:
lx

[array([[1, 0, 2, 0]]), array([[1, 0, 3, 0]]), array([[2, 0, 3, 0]])]

In [88]:
lx = np.array(lx)
lx

array([[[1, 0, 2, 0]],

       [[1, 0, 3, 0]],

       [[2, 0, 3, 0]]])

In [89]:
lx = np.concatenate(lx , axis=0)
lx

array([[1, 0, 2, 0],
       [1, 0, 3, 0],
       [2, 0, 3, 0]])

In [90]:
lx = lx.repeat(len(y) ,axis=0)
lx

array([[1, 0, 2, 0],
       [1, 0, 2, 0],
       [1, 0, 2, 0],
       [1, 0, 2, 0],
       [1, 0, 3, 0],
       [1, 0, 3, 0],
       [1, 0, 3, 0],
       [1, 0, 3, 0],
       [2, 0, 3, 0],
       [2, 0, 3, 0],
       [2, 0, 3, 0],
       [2, 0, 3, 0]])

In [91]:
y1 = y*len(x)
ly = np.array(y1)
ly =np.reshape(ly , (ly.shape[0],1))
ly1 = np.zeros_like(y1)
ly1 =np.reshape(ly1 , (ly1.shape[0],1))
ly = np.concatenate((ly1,ly) , axis = 1)
ly

array([[0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4]])

In [92]:
X = np.concatenate((lx,ly), axis=1)
X

array([[1, 0, 2, 0, 0, 1],
       [1, 0, 2, 0, 0, 2],
       [1, 0, 2, 0, 0, 3],
       [1, 0, 2, 0, 0, 4],
       [1, 0, 3, 0, 0, 1],
       [1, 0, 3, 0, 0, 2],
       [1, 0, 3, 0, 0, 3],
       [1, 0, 3, 0, 0, 4],
       [2, 0, 3, 0, 0, 1],
       [2, 0, 3, 0, 0, 2],
       [2, 0, 3, 0, 0, 3],
       [2, 0, 3, 0, 0, 4]])

In [93]:
for i in X:
    
    
    p1 = np.array([ i[0] , i[1] ])
    p2 = np.array([ i[2] , i[3] ])
    p3 = np.array([ i[4] , i[5] ])
    
    if p1[0]==p2[0] and p1[1]==p2[1]:
        continue
    print(p1,p2,p3)
    print(givemeans(p1,p2,p3))

[1 0] [2 0] [0 1]
0
[1 0] [2 0] [0 2]
0
[1 0] [2 0] [0 3]
0
[1 0] [2 0] [0 4]
0
[1 0] [3 0] [0 1]
0
[1 0] [3 0] [0 2]
0
[1 0] [3 0] [0 3]
0
[1 0] [3 0] [0 4]
0
[2 0] [3 0] [0 1]
0
[2 0] [3 0] [0 2]
0
[2 0] [3 0] [0 3]
0
[2 0] [3 0] [0 4]
0
