In [6]:
import numpy as np

In [16]:
a= np.array([ [1,2,3,4] ,
             [5,6,7,8] ,
             [9,10,11,12]])
print(a.shape)

(3, 4)


In [17]:

for i in a:
    print(i,type(i))

[1 2 3 4] <class 'numpy.ndarray'>
[5 6 7 8] <class 'numpy.ndarray'>
[ 9 10 11 12] <class 'numpy.ndarray'>


In [18]:
x=a[ : , 2 ]
y=a[ : , 2:3 ]
z1=a[2][3]
z2=a[2,3]
print(x,type(x),x.shape)
## 1,3

print(y,type(y),y.shape)
## 

[ 3  7 11] <class 'numpy.ndarray'> (3,)
[[ 3]
 [ 7]
 [11]] <class 'numpy.ndarray'> (3, 1)


In [20]:
dinp=input("hello")

hello


In [25]:
str=input
print(str)

<class 'str'>


In [30]:
str = '100'
  
print("int('100') with base 2 = ", int(str, 8))

int('100') with base 2 =  64


In [51]:
a=20
print(id(a))

140708369494880


In [52]:
d=dict()
d["name"]="CodingBlocks"

In [53]:
print(d["name"])


CodingBlocks


In [54]:
l=list([1,2,5,21,5,6,23,5])

In [55]:
s="naman"

In [56]:
print(len(l))

8


In [57]:
print(s)

naman


In [58]:
print(s.find("w"))
if 212 in l:
    l.index(212)
else:
    print("element not there")

-1
element not there


In [59]:
d=dict({"name":"coding blocks" , "age":29 , "married":True})

print(d.values())
print(d.keys())

print(d.items())

dict_values(['coding blocks', 29, True])
dict_keys(['name', 'age', 'married'])
dict_items([('name', 'coding blocks'), ('age', 29), ('married', True)])


In [60]:
if "name"  in d:
    print("yes")
    

yes


In [61]:
for i in d:
    print("the key is = {} and the corresponding value is : {} " .format(i,d[i]))

the key is = name and the corresponding value is : coding blocks 
the key is = age and the corresponding value is : 29 
the key is = married and the corresponding value is : True 


In [68]:
s=print(d.get("names"))

None


In [71]:
print(s)

None
